# Generated by Django 6.0.5 on 2026-05-25 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolNowMgt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetentionAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_type', models.CharField(choices=[('high_absenteeism', 'High Absenteeism'), ('low_grades', 'Low Grades'), ('fee_default', 'Fee Default'), ('other', 'Other')], max_length=30)),
                ('detail', models.TextField(help_text="Human-readable description, e.g. 'Absent 4 out of last 5 school days'")),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retention_alerts', to='SchoolNowMgt.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('provider_response', models.TextField(blank=True, help_text="Raw response from Africa's Talking API")),
                ('related_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='SchoolNowMgt.retentionalert')),
                ('related_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='SchoolNowMgt.staffprofile')),
                ('related_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='SchoolNowMgt.student')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='retentionalert',
            index=models.Index(fields=['student'], name='SchoolNowMg_student_e2061e_idx'),
        ),
        migrations.AddIndex(
            model_name='retentionalert',
            index=models.Index(fields=['resolved'], name='SchoolNowMg_resolve_90da98_idx'),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['status'], name='SchoolNowMg_status_5a06c3_idx'),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['sent_at'], name='SchoolNowMg_sent_at_e33241_idx'),
        ),
    ]
