# Generated by Django 6.0.5 on 2026-05-25 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolNowMgt', '0002_retentionalert_smslog_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
