# Generated by Django 6.0.5 on 2026-05-30 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SchoolNowMgt", "0003_alter_customuser_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
