# Generated by Django 6.0.5 on 2026-06-01 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolNowMgt', '0004_alter_customuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('quiz_submission', 'Quiz Submission'), ('message', 'Message'), ('system_backup', 'System Backup'), ('attendance_marked', 'Attendance Marked'), ('grade_entered', 'Grade Entered'), ('circular_sent', 'Circular Sent'), ('lesson_created', 'Lesson Created'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(default='info', help_text='Material Symbols icon name', max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('success', 'Success')], default='info', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('related_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='SchoolNowMgt.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='SchoolNowMgt.staffprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['teacher', '-created_at'], name='SchoolNowMg_teacher_ab4293_idx'), models.Index(fields=['activity_type'], name='SchoolNowMg_activit_10ab1c_idx')],
            },
        ),
        migrations.CreateModel(
            name='TeacherTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateTimeField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], db_index=True, default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('class_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_tasks', to='SchoolNowMgt.classgrade')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_tasks', to='SchoolNowMgt.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='SchoolNowMgt.staffprofile')),
            ],
            options={
                'ordering': ['-due_date'],
                'indexes': [models.Index(fields=['teacher', 'status'], name='SchoolNowMg_teacher_bf7623_idx'), models.Index(fields=['due_date'], name='SchoolNowMg_due_dat_e72e4e_idx')],
            },
        ),
    ]
