# Generated by Django 6.0.5 on 2026-06-09 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolNowMgt', '0005_activitylog_teachertask'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Template name (e.g., 'Low Attendance Alert')", max_length=200)),
                ('category', models.CharField(choices=[('attendance', 'Attendance Alert'), ('academic', 'Academic Performance'), ('event', 'School Event'), ('general', 'General Announcement'), ('discipline', 'Discipline Notice'), ('fees', 'Fee Payment')], max_length=20)),
                ('intended_for', models.CharField(choices=[('teacher', 'Teachers'), ('staff', 'Support Staff'), ('parent', 'Parents'), ('all', 'All')], default='all', help_text='Which role(s) this template is intended for', max_length=10)),
                ('body', models.TextField(help_text='Template body with optional placeholders: {student_name}, {parent_name}, {class_name}, {teacher_name}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_templates_created', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to='SchoolNowMgt.school')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('recipient_type', models.CharField(choices=[('all_teachers', 'All Teachers'), ('all_staff', 'All Support Staff'), ('all_staff_combined', 'All Teachers & Support Staff'), ('all_parents', 'All Parents'), ('class_specific', 'Parents of Specific Class'), ('individual', 'Individual User')], help_text='Targeting strategy for message recipients', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, help_text='If set, message will be delivered at this time (processed by cron). If null, delivered immediately.', null=True)),
                ('is_sent', models.BooleanField(db_index=True, default=False, help_text='Marks when message has been processed and recipients assigned')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='SchoolNowMgt.school')),
                ('sender', models.ForeignKey(limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_sent', to=settings.AUTH_USER_MODEL)),
                ('target_class', models.ForeignKey(blank=True, help_text="Used when recipient_type='class_specific'", null=True, on_delete=django.db.models.deletion.SET_NULL, to='SchoolNowMgt.classgrade')),
                ('target_user', models.ForeignKey(blank=True, help_text="Used when recipient_type='individual'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_targeted_to_user', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_using_template', to='SchoolNowMgt.messagetemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(blank=True, help_text='Timestamp when recipient marked message as read. Null if unread.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='SchoolNowMgt.message')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='SchoolNowMg_recipie_fa56ce_idx'), models.Index(fields=['read_at'], name='SchoolNowMg_read_at_9101a8_idx')],
                'unique_together': {('message', 'recipient')},
            },
        ),
        migrations.AddIndex(
            model_name='messagetemplate',
            index=models.Index(fields=['school', 'is_active'], name='SchoolNowMg_school__301a1b_idx'),
        ),
        migrations.AddIndex(
            model_name='messagetemplate',
            index=models.Index(fields=['category'], name='SchoolNowMg_categor_05e708_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['school', '-created_at'], name='SchoolNowMg_school__04b22e_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_sent', 'scheduled_at'], name='SchoolNowMg_is_sent_04834a_idx'),
        ),
    ]
