# Generated by Django 6.0.5 on 2026-06-09 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolNowMgt', '0006_messagetemplate_message_messagerecipient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Brief biography or professional summary')),
                ('department', models.CharField(blank=True, help_text='E.g., Administration, Leadership', max_length=100)),
                ('office_location', models.CharField(blank=True, help_text='Office location in school', max_length=255)),
                ('availability_hours', models.CharField(blank=True, help_text='E.g., 8:00 AM - 5:00 PM, Monday to Friday', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Profile',
                'verbose_name_plural': 'Admin Profiles',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('holiday', 'Holiday'), ('exam', 'Examination'), ('activity', 'School Activity'), ('meeting', 'Staff Meeting'), ('other', 'Other Event')], db_index=True, default='other', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_created', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='SchoolNowMgt.school')),
            ],
            options={
                'ordering': ['start_date'],
                'indexes': [models.Index(fields=['school', 'start_date'], name='SchoolNowMg_school__9e6ba4_idx'), models.Index(fields=['event_type', 'start_date'], name='SchoolNowMg_event_t_15a0e4_idx')],
            },
        ),
    ]
