# Generated by Django 6.0.5 on 2026-06-12 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolNowMgt', '0007_adminprofile_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_type',
            field=models.CharField(choices=[('admin', 'Admin/Staff'), ('parent', 'Parent')], default='admin', help_text='Whether message was sent by admin/staff or parent', max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_sent', to=settings.AUTH_USER_MODEL),
        ),
    ]
