# Generated by Django 6.0.5 on 2026-06-12 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolNowMgt', '0008_add_sender_type_to_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(blank=True, help_text='When the student submitted the assignment', null=True)),
                ('submission_text', models.TextField(blank=True, help_text="Student's assignment submission text or link to uploaded file")),
                ('status', models.CharField(choices=[('pending', 'Pending Submission'), ('submitted', 'Submitted'), ('graded', 'Graded'), ('late', 'Submitted Late'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=15)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, help_text='Grade out of 100 (if graded)', max_digits=5, null=True)),
                ('feedback', models.TextField(blank=True, help_text='Teacher feedback on the assignment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-assignment__due_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_date']},
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='SchoolNowMg_event_t_15a0e4_idx',
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type'], name='SchoolNowMg_event_t_33600f_idx'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='class_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='SchoolNowMgt.classgrade'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='SchoolNowMgt.subject'),
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='SchoolNowMgt.assignment'),
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_graded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='SchoolNowMgt.student'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['class_grade', 'subject'], name='SchoolNowMg_class_g_9971ef_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['due_date'], name='SchoolNowMg_due_dat_6f5787_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['created_by'], name='SchoolNowMg_created_28694a_idx'),
        ),
        migrations.AddIndex(
            model_name='studentassignment',
            index=models.Index(fields=['student', 'status'], name='SchoolNowMg_student_d6a864_idx'),
        ),
        migrations.AddIndex(
            model_name='studentassignment',
            index=models.Index(fields=['assignment', 'status'], name='SchoolNowMg_assignm_d3a265_idx'),
        ),
        migrations.AddIndex(
            model_name='studentassignment',
            index=models.Index(fields=['created_at'], name='SchoolNowMg_created_32b665_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentassignment',
            unique_together={('student', 'assignment')},
        ),
    ]
