# Generated by Django 6.0.5 on 2026-06-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolNowMgt', '0011_alter_message_sender_type_teacherattendance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classgrade',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='classgrade',
            name='curriculum',
            field=models.CharField(choices=[('national', 'Uganda National Curriculum'), ('international', 'International Curriculum')], db_index=True, default='national', max_length=20),
        ),
        migrations.AddField(
            model_name='grade',
            name='curriculum',
            field=models.CharField(choices=[('national', 'Uganda National Curriculum'), ('international', 'International Curriculum')], db_index=True, default='national', max_length=20),
        ),
        migrations.AddField(
            model_name='grade',
            name='semester',
            field=models.CharField(blank=True, choices=[('semester_1', 'Semester 1'), ('semester_2', 'Semester 2')], db_index=True, help_text='For International curriculum', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='curriculum',
            field=models.CharField(choices=[('national', 'Uganda National Curriculum'), ('international', 'International Curriculum')], db_index=True, default='national', max_length=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='curriculum',
            field=models.CharField(choices=[('national', 'Uganda National Curriculum'), ('international', 'International Curriculum')], db_index=True, default='national', max_length=20),
        ),
        migrations.AddField(
            model_name='timetable',
            name='curriculum',
            field=models.CharField(choices=[('national', 'Uganda National Curriculum'), ('international', 'International Curriculum')], db_index=True, default='national', max_length=20),
        ),
        migrations.AlterField(
            model_name='grade',
            name='term',
            field=models.CharField(blank=True, choices=[('term_1', 'Term 1'), ('term_2', 'Term 2'), ('term_3', 'Term 3')], db_index=True, help_text='For Uganda National curriculum', max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipient_type',
            field=models.CharField(choices=[('all_teachers', 'All Teachers'), ('all_staff', 'All Support Staff'), ('all_staff_combined', 'All Teachers & Support Staff'), ('all_parents', 'All Parents'), ('class_specific', 'Parents of Specific Class'), ('class_announcement', 'Class Announcement (Parents)'), ('individual_parent', 'Individual Parent'), ('specific_teacher', 'Specific Teacher'), ('individual', 'Individual User'), ('admin', 'School Admin')], help_text='Targeting strategy for message recipients', max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_type',
            field=models.CharField(choices=[('admin', 'Admin/Staff'), ('parent', 'Parent'), ('support_staff', 'Support Staff'), ('teacher', 'Teacher')], default='admin', help_text='Whether message was sent by admin/staff, parent, support staff, or teacher', max_length=15),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='classgrade',
            unique_together={('name', 'school', 'curriculum')},
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'subject', 'curriculum', 'term', 'semester', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'code', 'curriculum')},
        ),
    ]
