# Generated by Django 6.0.5 on 2026-06-15 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolNowMgt', '0012_alter_classgrade_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_in_time', models.TimeField(help_text='Time when break started')),
                ('break_out_time', models.TimeField(blank=True, help_text='Time when break ended. Null if break is still active.', null=True)),
                ('reason', models.CharField(blank=True, help_text='Reason for break (e.g., lunch, restroom, personal)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Break Session',
                'verbose_name_plural': 'Break Sessions',
                'ordering': ['teacher_attendance', 'break_in_time'],
            },
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='break_count',
            field=models.IntegerField(default=0, help_text='Number of breaks taken during the shift'),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='total_break_duration',
            field=models.IntegerField(default=0, help_text='Total break duration in minutes'),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='teacherattendance',
            index=models.Index(fields=['staff', '-date'], name='SchoolNowMg_staff_i_1251a7_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherattendance',
            index=models.Index(fields=['date'], name='SchoolNowMg_date_abfe80_idx'),
        ),
        migrations.AddField(
            model_name='breaksession',
            name='teacher_attendance',
            field=models.ForeignKey(help_text="Link to the teacher's shift attendance record", on_delete=django.db.models.deletion.CASCADE, related_name='break_sessions', to='SchoolNowMgt.teacherattendance'),
        ),
        migrations.AddIndex(
            model_name='breaksession',
            index=models.Index(fields=['teacher_attendance', '-break_in_time'], name='SchoolNowMg_teacher_009ef4_idx'),
        ),
    ]
