# Generated by Django 6.0.5 on 2026-06-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolNowMgt', '0014_curriculum_subject_curriculum_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, help_text='Subjects this teacher is qualified to teach', related_name='teachers', to='SchoolNowMgt.subject'),
        ),
    ]
