# Generated by Django 6.0.5 on 2026-06-18 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolNowMgt', '0015_staffprofile_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='assigned_shift_supervisor',
            field=models.ForeignKey(blank=True, help_text='Supervisor this staff member reports to', limit_choices_to={'support_staff_role': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_staff', to='SchoolNowMgt.staffprofile'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='support_staff_role',
            field=models.CharField(choices=[('staff', 'Regular Staff Member'), ('supervisor', 'Shift Supervisor'), ('department_head', 'Department Head'), ('welfare_coordinator', 'Welfare Coordinator')], default='staff', help_text='Administrative role within support staff', max_length=50),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='teacher_admin_role',
            field=models.CharField(choices=[('teacher', 'Class/Subject Teacher'), ('dos', 'Director of Studies'), ('department_head', 'Subject Department Head'), ('head_teacher', 'Head Teacher')], default='teacher', help_text='Administrative role if teacher has one', max_length=50),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department_type', models.CharField(choices=[('security', 'Security (Askaris)'), ('matron', 'Matrons/Hostels'), ('catering', 'Kitchen/Catering'), ('cleaning', 'Cleaning/Housekeeping'), ('maintenance', 'Maintenance & Grounds'), ('health', 'Health & Wellness'), ('welfare', 'Welfare & Counseling'), ('transport', 'Transport & Drivers'), ('library', 'Library'), ('laboratory', 'Laboratory'), ('it', 'IT & Computer'), ('reception', 'Reception & Admin'), ('facilities', 'Facilities Management'), ('sports', 'Sports & Recreation'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('monthly_budget', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly budget allocation in local currency', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('head_of_department', models.ForeignKey(blank=True, limit_choices_to={'user__role': 'non_teaching_staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heads_support_department', to='SchoolNowMgt.staffprofile')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_departments', to='SchoolNowMgt.school')),
            ],
            options={
                'verbose_name_plural': 'Support Departments',
                'unique_together': {('school', 'department_type')},
            },
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='support_department',
            field=models.ForeignKey(blank=True, help_text='Department for non-teaching staff', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_staff_members', to='SchoolNowMgt.department'),
        ),
        migrations.CreateModel(
            name='TeacherDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department_type', models.CharField(choices=[('mathematics', 'Mathematics'), ('science', 'Science'), ('languages', 'Languages'), ('social_studies', 'Social Studies'), ('technology', 'Technology & ICT'), ('pe_sports', 'Physical Education & Sports'), ('arts_music', 'Arts & Music'), ('humanities', 'Humanities'), ('vocational', 'Vocational Studies'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('annual_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('head_of_department', models.ForeignKey(blank=True, limit_choices_to={'user__role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heads_teacher_department', to='SchoolNowMgt.staffprofile')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_departments', to='SchoolNowMgt.school')),
            ],
            options={
                'verbose_name_plural': 'Teacher Departments',
                'unique_together': {('school', 'department_type')},
            },
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='teacher_department',
            field=models.ForeignKey(blank=True, help_text='Subject department this teacher belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_members', to='SchoolNowMgt.teacherdepartment'),
        ),
        migrations.CreateModel(
            name='ClassTeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('class_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher_assignments', to='SchoolNowMgt.classgrade')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolNowMgt.school')),
                ('teacher', models.ForeignKey(limit_choices_to={'user__role': 'teacher'}, on_delete=django.db.models.deletion.PROTECT, related_name='class_teacher_assignments', to='SchoolNowMgt.staffprofile')),
            ],
            options={
                'unique_together': {('school', 'class_grade', 'academic_year')},
            },
        ),
    ]
