# Generated by Django 6.0.5 on 2026-06-19 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolNowMgt', '0016_staffprofile_assigned_shift_supervisor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hostel_type', models.CharField(choices=[('boys', 'Boys Hostel'), ('girls', 'Girls Hostel'), ('mixed', 'Mixed Hostel')], max_length=20)),
                ('capacity', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matron', models.OneToOneField(blank=True, limit_choices_to={'support_staff_role': 'welfare_coordinator', 'user__role': 'non_teaching_staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manages_hostel', to='SchoolNowMgt.staffprofile')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostels', to='SchoolNowMgt.school')),
            ],
            options={
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ResidentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(blank=True, max_length=20)),
                ('assignment_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('transferred', 'Transferred'), ('graduated', 'Graduated')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='SchoolNowMgt.hostel')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='hostel_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('hostel', 'student')},
            },
        ),
    ]
