# Generated by Django 6.0.5 on 2026-06-19 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolNowMgt', '0017_hostel_residentassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='school',
            field=models.ForeignKey(blank=True, help_text='School assignment. NULL for parents (who access multiple schools).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='SchoolNowMgt.school'),
        ),
        migrations.CreateModel(
            name='StudentParentRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('guardian', 'Guardian'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('grandparent', 'Grandparent'), ('other', 'Other')], default='parent', max_length=20)),
                ('is_primary_guardian', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_linked', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='parent_relationships', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(help_text='School where this student is enrolled', on_delete=django.db.models.deletion.CASCADE, to='SchoolNowMgt.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_relationships', to='SchoolNowMgt.student')),
            ],
            options={
                'verbose_name_plural': 'Student Parent Relationships',
                'unique_together': {('parent', 'student', 'school')},
            },
        ),
    ]
