# Generated by Django 6.0.5 on 2026-06-19 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolNowMgt', '0018_alter_customuser_school_studentparentrelationship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminprofile',
            options={},
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('grade_posted', 'Grade Posted'), ('payment_due', 'Payment Due'), ('payment_overdue', 'Payment Overdue'), ('attendance_alert', 'Attendance Alert'), ('assignment_due', 'Assignment Due'), ('event_reminder', 'Event Reminder'), ('schedule_change', 'Schedule Change'), ('message', 'New Message'), ('announcement', 'Announcement'), ('admin_alert', 'Admin Alert'), ('system_alert', 'System Alert'), ('other', 'Other')], default='other', help_text='Type of notification', max_length=30)),
                ('title', models.CharField(help_text='Short notification title', max_length=200)),
                ('message', models.TextField(help_text='Detailed notification message')),
                ('is_read', models.BooleanField(default=False, help_text='Whether user has read this notification')),
                ('read_at', models.DateTimeField(blank=True, help_text='When user read the notification', null=True)),
                ('action_url', models.CharField(blank=True, help_text='URL to relevant page (e.g., grades view, payment detail)', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When notification was created')),
                ('recipient', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_event', models.ForeignKey(blank=True, help_text='Event related notification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_notifications', to='SchoolNowMgt.event')),
                ('related_grade', models.ForeignKey(blank=True, help_text='Grade posted notification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_notifications', to='SchoolNowMgt.grade')),
                ('related_message', models.ForeignKey(blank=True, help_text='Message notification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_notifications', to='SchoolNowMgt.message')),
                ('related_payment', models.ForeignKey(blank=True, help_text='Payment related notification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_notifications', to='SchoolNowMgt.feepayment')),
                ('related_student', models.ForeignKey(blank=True, help_text='Student related to notification (e.g., for grade/attendance)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_notifications', to='SchoolNowMgt.student')),
            ],
            options={
                'verbose_name': 'Admin Profile',
                'verbose_name_plural': 'Admin Profiles',
            },
        ),
    ]
