# Generated by Django 6.0.5 on 2026-06-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolNowMgt', '0019_add_notification_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='teacher_admin_role',
            field=models.CharField(choices=[('teacher', 'Class/Subject Teacher'), ('dos', 'Director of Studies'), ('department_head', 'Subject Department Head'), ('head_teacher', 'Head Teacher'), ('deputy_hm', 'Deputy Headmaster')], default='teacher', help_text='Administrative role if teacher has one', max_length=50),
        ),
    ]
