# Generated by Django 6.0.6 on 2026-08-04 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolNowMgt', '0020_alter_staffprofile_teacher_admin_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentparentrelationship',
            name='relationship_type',
            field=models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('guardian', 'Guardian'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('grandparent', 'Grandparent'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.CreateModel(
            name='RollCallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('present_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_roll_call_sessions', to='SchoolNowMgt.staffprofile')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roll_call_sessions', to='SchoolNowMgt.hostel')),
            ],
            options={
                'verbose_name': 'Roll Call Session',
                'verbose_name_plural': 'Roll Call Sessions',
                'ordering': ['-started_at'],
            },
        ),
    ]
