# Generated by Django 6.0.6 on 2026-08-12 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolNowMgt', '0021_alter_studentparentrelationship_relationship_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_date', models.DateField(db_index=True, help_text='Date of the lesson')),
                ('topic', models.CharField(help_text='Topic or title of the lesson', max_length=200)),
                ('objective', models.TextField(help_text='Learning objectives for this lesson')),
                ('activities', models.TextField(blank=True, help_text='Learning activities and exercises')),
                ('resources', models.TextField(blank=True, help_text='Materials and resources needed')),
                ('homework', models.TextField(blank=True, help_text='Homework assignment if any')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='SchoolNowMgt.classgrade')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='SchoolNowMgt.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'user__role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='SchoolNowMgt.staffprofile')),
            ],
            options={
                'verbose_name': 'Lesson Plan',
                'verbose_name_plural': 'Lesson Plans',
                'ordering': ['-lesson_date', 'class_grade'],
                'indexes': [models.Index(fields=['teacher', '-lesson_date'], name='SchoolNowMg_teacher_bfe6a7_idx'), models.Index(fields=['lesson_date'], name='SchoolNowMg_lesson__6422f8_idx')],
            },
        ),
    ]
