# Generated by Django 6.0.6 on 2026-08-12 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolNowMgt', '0022_lessonplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='lesson_end_time',
            field=models.TimeField(blank=True, help_text='End time of the lesson (for edit window calculation)', null=True),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='lesson_start_time',
            field=models.TimeField(blank=True, help_text='Start time of the lesson (for edit window calculation)', null=True),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='timetable',
            field=models.ForeignKey(blank=True, help_text='Optional link to the scheduled timetable entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_plans', to='SchoolNowMgt.timetable'),
        ),
    ]
