# Generated by Django 6.0.6 on 2026-08-14 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolNowMgt', '0023_lessonplan_lesson_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='review_status',
            field=models.CharField(
                choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')],
                db_index=True,
                default='pending',
                help_text='Approval status from DOS',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='reviewed_by',
            field=models.ForeignKey(
                blank=True,
                help_text='DOS staff who reviewed this plan',
                limit_choices_to={'teacher_admin_role': 'dos', 'user__role': 'teacher'},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='reviewed_lesson_plans',
                to='SchoolNowMgt.staffprofile'
            ),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When the plan was reviewed', null=True),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='review_notes',
            field=models.TextField(blank=True, help_text='DOS feedback or rejection reason'),
        ),
    ]
